apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-project
  namespace: 3scale-project
spec:
  channel: threescale-2.10
  name: 3scale-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
